#define GAME_WIDTH 800
#define GAME_HEIGHT 600
#define GAME_SCALING_FACTOR 0.95f
#define GAME_GRAVITY 1

#define SHEEP_XPOS 50
#define SHEEP_YPOS 0.52f * GAME_HEIGHT

#define FLOOR_YPOS 0.75f * GAME_HEIGHT

#define OBSTACLE_JMP_Y 300
#define OBSTACLE_DCK_Y 410

#define OBSTACLE_COOLDOWN 2000.0f

